plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

android {
    namespace 'com.copilot.soundnotifywearos'
    compileSdk 35

    defaultConfig {
        applicationId "com.copilot.soundnotifywearos"
        minSdk 30
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        compose true
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.activity:activity-compose:1.9.0'
    implementation 'androidx.wear.compose:compose-material:1.3.1'
    implementation 'androidx.wear.compose:compose-foundation:1.3.1'
    implementation 'androidx.compose.material:material-icons-core:1.6.7'
    implementation 'androidx.compose.ui:ui-tooling-preview:1.6.7'
    debugImplementation 'androidx.compose.ui:ui-tooling:1.6.7'
}
